### ISSUE TITLE
2.2 Plan

### ISSUE THREAD

**Issue by gampleman** [gampleman/elm-visualization#73]
For a long time I've made modules with (hopefully) a relatively coherent API that tackle some sort of problem. Usually I've omitted some of the slightly less used parts to save some time and get stuff out of the door. 

But I believe it's time to make a release that fills out those blanks to make a more comprehensive library.

So here is the checklist what I would like to see done:

- Force (#117)
  - [x] `collision` force :mag:
  - [x] `x` force
  - [x] `y` force
  - [x] `radial` force :mag:
- Interpolation
  - [x] LAB and HCL color interpolators (#76)
  - [ ] Cubehelix and XYZ color interpolators
- Scale (#85)
  - [x] Radial @gampleman 
  - [x] Diverging :mag: @gampleman 
  - [x] Quantile @gampleman 
  - [x] Threshold @gampleman 
  - [x] Point @gampleman 
- Scale.Color
   - [x] Eh, this could use a whole lot... #61
- Shape - I think this is fairly complete for now
- Statistics
   - [x] Ship #58 :mag: (@gampleman)
- Transition
  - [x] Add all the common easing functions #77 
- Zoom
  - [ ] Add documentation and example on how to use in an interactive SVG. There are some subtleties like weird event handling and tricky coordinate conversions that should be easier to setup. :mag:
  - [ ] Add functions to manipulate the zoom programmatically.
- Examples
  - [x] Rework some of the more complex examples to be a bit more didactical. Probably the stacked charts are a bit confusing. 
   - [x] Get rid of the SampleData module and just inline the data definitions (#90).
   - [x] Write a bit more introductory text to outline what techniques the example is there to show.
   - [x] Implement categories for the sample website #95
   - [x] Implement a "Open on Ellie" link #95
   - [x] Figure out how to effectively redirect from the old docs site to the new. Ideally if we can remove the compiled assets from the repo, this would be best.
- Docs
   - [x] Fix any typos or broken images
   - [x] Link up Interpolation and Sequential scales.
   - [x] Uppercase README.md to make it work with edp on case sensitive operating systems (@gampleman)
- Project
   - [x] Migrate CI to GitHub actions. 
   - [x] Fix tests to not fail due to random perturbations in Floating point numbers #73 @Anton-4 
   - [x] Update to elm-geometry v3 (if ready sooner, can be released as 2.1.2)

Probably drop:

  - [Fisheye](https://observablehq.com/@benmaier/a-visually-more-appealing-fisheye-function) scale :mag:
  - Think about timelines for transitions :mag:
  - Document various contributing minutiae so that the project can be maintained without me if necessary

(:mag: means that this feature will also need an example demonstrating how to use it).

This is a fairly ambitions plan and I would appreciate some help. Typically a lot of the design of these apis should simply follow the patterns already established in the module (remember, this will be a MINOR release, so no breaking changes allowed). As such this will be mostly about implementation, docs and examples. (Of course if while working on these you think you discovered a better API design, please open an issue or get in touch on Slack. Just because we won't ship it in this release doesn't mean we won't improve it at all. But I do like to batch breaking changes so the library mostly provides a stable target with only very rare upgrade costs).

So if you would like to contribute one of these, please let me know. Thanks!

**Comment by sturgman** [comment]
I would like to contribute more than this but I don't think I have the skills. This is what I can help with:

- Examples - reworking them for didactical purposes
- Examples - Get rid of the SampleData module and inline data definitions
- Examples - Categories if that is what you want to do
- Docs - Look for typos and broken images

I know this is the easy stuff but I am more a user that wants to help than a real developer. Let me know if it would be useful!

**Comment by deciob** [comment]
I could be interested in helping out with the the Scale.Color module. 
Maybe also at revisiting/adding some examples.

**Comment by gampleman** [comment]
@sturgman Yes all of these are very helpful, thank you!

@deciob https://github.com/d3/d3-scale-chromatic is potentially a good starting point, but some thought should probably be given on it. In general I would like a reasonable selection of categorical, diverging, single-hue and maybe a nice cyclical. But it's a bit up to you (if you chose to proceed of course) on what kinds of color scales to include.

**Comment by deciob** [comment]
@gampleman I agree. I can start by revising existing colour schemes and then we can discuss. I hope to find some time before the end of this week to start having a look, but cannot guarantee it.

**Comment by deciob** [comment]
@gampleman today I had a play with some colour interpolations. For now this is mostly experimentation for me to get my head around the argument. I am happy to keep on working on this, but would be a bit slow...

https://github.com/deciob/elm-visualization/pull/1

**Comment by gampleman** [comment]
@deciob FYI I've done some work on this before: https://github.com/avh4/elm-color/pull/23

**Comment by deciob** [comment]
@gampleman nice, will have a look at that

**Comment by deciob** [comment]
@gampleman one obvious thought is why not move your work into the Scale.Color module? That would be a great starting point for adding perceptually uniform colour palettes.

**Comment by gampleman** [comment]
I was thinking of moving them to the `Interpolation` module, which seems a reasonable place for interpolators to live :), especially since elm-color is not interested in colourspace interpolation.

However, Scale.Color can easily depend on these. I'm quite busy with other stuff (i.e. #58) so go ahead if you like. Also feel free to get in touch on the elm slack if you need any help/coordination.

**Comment by deciob** [comment]
@gampleman I will be off this weekend, but if you are not in a hurry, from next week I am still happy to look into the colour palettes and the Scale.Color module. I would also like to look into one of the stacked bar chart examples, if you are happy with that.

**Comment by deciob** [comment]
> @gampleman I will be off this weekend, but if you are not in a hurry, from next week I am still happy to look into the colour palettes and the Scale.Color module. I would also like to look into one of the stacked bar chart examples, if you are happy with that.

@gampleman with the coronavirus lock down, it has been a bit of a chaos on my side so haven't looked into anything of this in the past month. Not sure at what stage you are at, but if still relevant, I can try to have a look into this again.

**Comment by gampleman** [comment]
@deciob Well I have been down with the Coronavirus for a couple of weeks (I'm still recovering). In the meantime I have been working on the `Scale` module, so all of the above is still available.

**Comment by deciob** [comment]
@gampleman I might have had it too, but with mild symptoms. Hope you finish recovering asp. I will see what I can do over the weekend and will keep you posted.

**Comment by Anton-4** [comment]
@gampleman I'm willing to do "Update to elm-geometry v3".

**Comment by gampleman** [comment]
Hey @Anton-4, there is some context to be aware of. I’d recommend taking a look at https://discourse.elm-lang.org/t/project-idea-prefixed-package-generator/5297. 

@pd-andy started some work on the package prefixer (see https://github.com/pd-andy/elm-package-prefixer), but it is worth coordinating with @pd-andy about it. 

Thanks again for all your effort!

**Comment by Anton-4** [comment]
The part of the iceberg underneath the water :stuck_out_tongue:.
I will get in touch with @pd-andy, happy to help!

**Comment by Anton-4** [comment]
I have just submitted a PR to the package prefixer and will continue to look at that.
@gampleman For "Get rid of the SampleData module..." would you prefer random functions that generate data or plain hard coded data?

**Comment by gampleman** [comment]
@Anton-4 The intention there is to simplify the examples to be self contained to help beginners understand the code easier (see some of the comments in #39). So most likely it would be sufficient to simply copy-paste the data literals from sample-data into the relevant modules. (This may of course create some duplication, but I think that's perfectly fine for didactical reasons).

The secondary motivation here is to make the examples self contained so that they can work well as Ellies.

**Comment by varunbhoopalam** [comment]
Hello,

In my own project I would love a bounding box . I am unsure of how to implement that given the available methods on the force api. Do you know how to implement a bounding box using what's currently available in the force module? If not easy/possible, would any of the wishlist force methods to be implemented help with this? I am happy to offer help to this library to get this feature!

**Comment by gampleman** [comment]
Thank you everyone for helping with this fairly ambitious plan. We completed a huge amount of work. Not everything made it, but I think shipping these improvements rather than waiting for the "perfect" release is important.
